// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.26.1
// source: pkg/proto_stream/proto/tcp_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TCPMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // `ping`, `tcp_handshake`, `message`, `encrypted_message`, etc.
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPMessage) Reset() {
	*x = TCPMessage{}
	mi := &file_pkg_proto_stream_proto_tcp_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPMessage) ProtoMessage() {}

func (x *TCPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_stream_proto_tcp_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPMessage.ProtoReflect.Descriptor instead.
func (*TCPMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_stream_proto_tcp_message_proto_rawDescGZIP(), []int{0}
}

func (x *TCPMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TCPMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pkg_proto_stream_proto_tcp_message_proto protoreflect.FileDescriptor

var file_pkg_proto_stream_proto_tcp_message_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x63, 0x70, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3a, 0x0a, 0x0a, 0x54, 0x43, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x15, 0x5a,
	0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pkg_proto_stream_proto_tcp_message_proto_rawDescOnce sync.Once
	file_pkg_proto_stream_proto_tcp_message_proto_rawDescData []byte
)

func file_pkg_proto_stream_proto_tcp_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_stream_proto_tcp_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_stream_proto_tcp_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_stream_proto_tcp_message_proto_rawDesc), len(file_pkg_proto_stream_proto_tcp_message_proto_rawDesc)))
	})
	return file_pkg_proto_stream_proto_tcp_message_proto_rawDescData
}

var file_pkg_proto_stream_proto_tcp_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_stream_proto_tcp_message_proto_goTypes = []any{
	(*TCPMessage)(nil), // 0: proto.TCPMessage
}
var file_pkg_proto_stream_proto_tcp_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_stream_proto_tcp_message_proto_init() }
func file_pkg_proto_stream_proto_tcp_message_proto_init() {
	if File_pkg_proto_stream_proto_tcp_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_stream_proto_tcp_message_proto_rawDesc), len(file_pkg_proto_stream_proto_tcp_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_stream_proto_tcp_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_stream_proto_tcp_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_stream_proto_tcp_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_stream_proto_tcp_message_proto = out.File
	file_pkg_proto_stream_proto_tcp_message_proto_goTypes = nil
	file_pkg_proto_stream_proto_tcp_message_proto_depIdxs = nil
}
